In [2]:
import pandas as pd
import numpy as np
import os
os.chdir('C:/Users/COOPER/Desktop/1340 MID') 
table7 = pd.read_excel("UN_MigrantStockTotal_2015.xlsx",sheet_name = "ANNEX", index_col=[0], skiprows=14)

# Rename some columns since they have the same name but actually different value under the column

In [6]:
table7.columns = [ 'Country name', 'Country sort order',
       'Major area', 'Major area code',
       'Major area sort order', 'Region', 
       'Region code', 'Region sort order',
       'Developed region', 'Least developed country',
       'Sub-Saharan Africa']
table7.reset_index(inplace=True)
table7

,Country code,Country name,Country sort order,Major area,Major area code,Major area sort order,Region,Region code,Region sort order,Developed region,Least developed country,Sub-Saharan Africa
0,4,Afghanistan,99,Asia,935,71,Southern Asia,5501,98,No,Yes,No
1,8,Albania,154,Europe,908,127,Southern Europe,925,153,Yes,No,No
2,12,Algeria,40,Africa,903,7,Northern Africa,912,39,No,No,No
3,16,American Samoa,257,Oceania,909,238,Polynesia,957,256,No,No,No
4,20,Andorra,155,Europe,908,127,Southern Europe,925,153,Yes,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...
227,876,Wallis and Futuna Islands,265,Oceania,909,238,Polynesia,957,256,No,No,No
228,732,Western Sahara,46,Africa,903,7,Northern Africa,912,39,No,No,No
229,887,Yemen,126,Asia,935,71,Western Asia,922,108,No,Yes,No
230,894,Zambia,27,Africa,903,7,Eastern Africa,910,8,No,Yes,Yes
231,716,Zimbabwe,28,Africa,903,7,Eastern Africa,910,8,No,No,Yes